name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Build Phase 2
        env:
          VITE_PHASE2: '1'
        run: npm run build
      - name: Verify build output
        run: |
          echo "Files in dist before rename:"
          ls -la dist/
          mv dist/index-phase2.html dist/index.html
          echo "Files in dist after rename:"
          ls -la dist/
          echo "Contents of index.html (first 5 lines):"
          head -5 dist/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4
